

//AUTHENTICATION ACTIONS
export const LOGIN_USER = 'LOGIN_USER';
export const UNAUTHORIZED = "UNAUTHORIZED";


//USER ACTION



//INVENTORY ACTIONS
export const SET_INVENTORIES = 'SET_INVENTORIES';
export const CLEAR_INVENTORIES = 'CLEAR_INVENTORIES';
export const UPDATE_INVENTORY = 'UPDATE_INVENTORY';
export const CREATE_INVENTORY = 'CREATE_INVENTORY';
export const DELETE_INVENTORY = 'DELETE_INVENTORY';

//AREA ACTIONS
export const SET_AREAS = 'SET_AREAS';
export const CLEAR_AREAS = 'CLEAR_AREAS';
export const UPDATE_AREA = 'UPDATE_AREA';
export const CREATE_AREA = 'CREATE_AREA';
export const DELETE_AREA = 'DELETE_AREA';

//ITEMS ACTIONS
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const CREATE_ITEM = 'CREATE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';



//MESSAGE ACTIONS

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';







