

//AUTHENTICATION ACTIONS
export const LOGIN_USER = 'LOGIN_USER';
export const UNAUTHORIZED = "UNAUTHORIZED";
export const INVALID_CREDENTIALS = 'LOGIN_INVALID_CREDENTIALS';
export const FAILED_TO_LOGIN= 'LOGIN_FAILED_TO_LOGIN';
export const SUCCESSFUL_LOGIN= 'LOGIN_SUCCESSFUL_LOGIN';
export const LOG_OUT='LOG_OUT';


//USER ACTION



//INVENTORY ACTIONS
export const SET_INVENTORIES = 'SET_INVENTORIES';
export const CLEAR_INVENTORIES = 'CLEAR_INVENTORIES';
export const UPDATE_INVENTORY = 'UPDATE_INVENTORY';
export const CREATE_INVENTORY = 'CREATE_INVENTORY';
export const DELETE_INVENTORY = 'DELETE_INVENTORY';
export const SET_CURRENT_INVENTORY = 'SET_CURRENT_INVENTORY';
export const CLEAR_CURRENT_INVENTORY = 'CLEAR_CURRENT_INVENTORY';

//AREA ACTIONS
export const SET_AREAS = 'SET_AREAS';
export const CLEAR_AREAS = 'CLEAR_AREAS';
export const UPDATE_AREA = 'UPDATE_AREA';
export const CREATE_AREA = 'CREATE_AREA';
export const DELETE_AREA = 'DELETE_AREA';
export const SET_CURRENT_AREA = 'SET_CURRENT_AREA';
export const CLEAR_CURRENT_AREA = 'CLEAR_CURRENT_AREA';

//ITEMS ACTIONS
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const CREATE_ITEM = 'CREATE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';



//MESSAGE ACTIONS

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';







